AWSTemplateFormatVersion: "2010-09-09"
Description: CICD pipeline to build a CloudFormation module out of a Stage repository

Parameters:
  pSharedDevOpsAccountId:
    Type: String
    Default: "{{resolve:ssm:/SDLF/Misc/DevOpsAccountId}}"
  pEnvironment:
    Type: String
    Default: "{{resolve:ssm:/SDLF/Misc/pEnv}}"
  pStageRepository:
    Type: String
  pStageName:
    Description: Name of the stage (letters, numbers and hyphen allowed, no other symbols or spaces)
    Type: String
    AllowedPattern: "[a-zA-Z0-9\\-]{1,12}"
    ConstraintDescription: "letters (uppercase and lowercase), numbers and hyphen allowed - 12 characters maximum"
  pTeamName:
    Type: String
  pSharedDevOpsAccountKmsKeyArn:
    Description: Arn of the KMS key in the Shared DevOps account
    Type: String
  pArtifactsBucket:
    Description: The artifactory bucket used by CodeBuild and CodePipeline
    Type: String
    Default: "{{resolve:ssm:/SDLF/S3/CFNBucket}}"
  pEventBridgeRepositoryTriggerRoleArn:
    Type: String
    Default: "{{resolve:ssm:/SDLF/IAM/EventBridgeRepositoryTriggerRoleArn}}"

Mappings:
  pCodeCommitBranch:
    dev:
      branch: dev
    test:
      branch: test
    prod:
      branch: master

Resources:
  rStageModulePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: "{{resolve:ssm:/SDLF/CodeBuild/CodePipelineRole}}"
      Stages:
        -
          Name: Source
          Actions:
            -
              Name: Source
              RoleArn: !Sub arn:aws:iam::${pSharedDevOpsAccountId}:role/sdlf-cicd-module-codecommit-${pEnvironment}
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: '1'
                Provider: CodeCommit
              OutputArtifacts:
                - Name: SourceArtifact
              Configuration:
                RepositoryName: !Ref pStageRepository
                BranchName: !FindInMap [pCodeCommitBranch, !Ref pEnvironment, branch]
                PollForSourceChanges: false
              RunOrder: 1
        -
          Name: Build
          Actions:
            -
              Name: Build
              InputArtifacts:
              - Name: SourceArtifact
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: '1'
                Provider: CodeBuild
              OutputArtifacts:
                - Name: BuildArtifact
              Configuration:
                ProjectName: "{{resolve:ssm:/SDLF/CodeBuild/BuildCloudformationModuleStage}}"
                EnvironmentVariables: !Sub '[{"name":"MODULE_NAME", "value":"${pTeamName}${pStageName}", "type":"PLAINTEXT"}]'
              RunOrder: 1
      ArtifactStore:
        Type: S3
        EncryptionKey:
          Id: !Ref pSharedDevOpsAccountKmsKeyArn
          Type: KMS
        Location: !Ref pArtifactsBucket

  rStageModuleTriggerEventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: !Sub "Run Stage State Machine on ${pStageName} repository update"
      EventPattern:
        source:
          - aws.codecommit
        detail-type:
          - CodeCommit Repository State Change
        resources:
          - !Sub arn:aws:codecommit:${AWS::Region}:${pSharedDevOpsAccountId}:${pStageRepository}
        detail:
          event:
            - referenceCreated
            - referenceUpdated
          referenceType:
            - branch
          referenceName:
            - dev
            - test
            - master
      Targets:
        - Arn: !Sub arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${rStageModulePipeline}
          Id: !Sub sdlf-${pStageRepository}-trigger
          RoleArn: !Ref pEventBridgeRepositoryTriggerRoleArn