AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Data Quality And Glue Catalog Tables Schema Replication

Parameters:
  pDataLakeAdminRoleArn:
    Type: String
  pEnvironment:
    Type: String
  pKMSKeyId:
    Type: String
  pCloudWatchLogsRetentionInDays:
    Type: Number

Globals:
  Function:
    Runtime: python3.9
    Handler: lambda_function.lambda_handler
    KmsKeyArn: !Ref pKMSKeyId

Resources:
  ######## LAMBDA #########
  rLambdaReplicate:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sdlf-glue-replication
      Description: Replicates Glue Catalog Metadata and Data Quality to Octagon Schemas Table
      CodeUri: ../lambda/replicate/src
      Environment:
        Variables:
          ENV: !Ref pEnvironment
      MemorySize: 128
      Timeout: 300
      Role: !Ref pDataLakeAdminRoleArn

  rLambdaReplicateLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${rLambdaReplicate}
      RetentionInDays: !Ref pCloudWatchLogsRetentionInDays
      KmsKeyId: !Ref pKMSKeyId

  rEventsInvokeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Ref: rLambdaReplicate
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt rLambdaEventsRule.Arn

  ######## EVENTS #########
  rLambdaEventsRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Triggers Glue replicate Lambda upon change to metadata catalog
      State: ENABLED
      EventPattern:
        source:
          - aws.glue
        detail-type:
          - Glue Data Catalog Database State Change
          - Glue Data Catalog Table State Change
      Targets:
        - Arn: !GetAtt rLambdaReplicate.Arn
          Id: LambdaReplicate

  ######## SSM #########
Outputs:
  oLambdaReplicate:
    Value: !Ref rLambdaReplicate
    Description: Replicates Glue Catalog Metadata and Data Quality to Octagon Schemas Table
