AWSTemplateFormatVersion: 2010-09-09
Description: Prerequisites for the rest of SDLF to be deployed/used

Parameters:
  pCustomBucketPrefix:
    Description: S3 Bucket Prefix if different from default. Must be a valid S3 Bucket name
    Type: String
    Default: sdlf

Resources:
  ######## S3 #########
  rArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${pCustomBucketPrefix}-cicd-cfn-artifacts-${AWS::Region}-${AWS::AccountId}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True

  rArtifactsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref rArtifactsBucket
      PolicyDocument:
        Statement:
          - Effect: Deny
            Principal: "*"
            Action: s3:*
            Resource:
              - !Sub ${rArtifactsBucket.Arn}/*
              - !GetAtt rArtifactsBucket.Arn
            Condition:
              Bool:
                aws:SecureTransport: False

  rArtifactsBucketSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/S3/DevOpsArtifactsBucket
      Type: String
      Value: !Ref rArtifactsBucket
      Description: S3 DevOps Artifacts Bucket